version: '3'
services:
  backend:
    build: .
    container_name: mks-backend
    ports:
      - 3333:3333
    volumes:
      - ./:/home/node/app
    networks:
      - my-network
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASS=123456
      - DB_NAME=mks-db
      - DB_PORT=5432

  db:
    image: postgres:latest
    container_name: mks-db
    ports:  
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=mks-db
    networks:
      - my-network

networks:
  my-network:
    driver: bridge